sudo: required
env:
  global:
  - VLC_ANDROID_TAG=3.1.6
services:
- docker
script:
- echo "testcontent" > ./tt
deploy:
  provider: releases
  api_key:
    secure: rBfAcLRZ+IAck4XPQVw/7hxbKesqEQzeJrpd3bDX912/RkdgzDtSmMQcFPaV6yZq9FDv2y5pa+S7IkGV7wxDCk/T9oMX+LKRZP3BVRpRea2GAOVIn7dsdfbnzGLZi9Mb11EoKY+6AqhwJWKsGouUmPlJECbICFGxmDC9OoOiUpeY+n4JoeoaQERasxIwKmAAV0IajzusJ2g+0GbxBSEX5wsyr3XbvOYM+fBTsJg8CExSAcXvRXawnCiEnLDvcYH36ENc4/njPoolNruMCVYlb3d8weftPoW/JcZIblXBUwLYVzS8Xu2yZAZyH11U4XiVjghPKvBUcCtMelrd0UngD+By40Sh+w6oxgydxmMLxcveLRwItt6bW/mXFY0eJAizCqLxgS6gBgzw48pvpVF0zCINckbNPfeFc5AAh4IY+SJm4Pe9PRqqtckG+RUSBSgo+rtmq9yMsxvhr2Wh09xXg745lvUI8hsGNOf1AQ5AdwRG0OQ3eCh6BFUq57fhXP9lPEjVANbI21fbUpHoUOMsl0/QUyjhdEXe83niBQhyUUP7DyZ0Iaj9iuCO7ibdX8P2abR3KLOXCwNSUywuaHJ7wlQVfhpzYBGTCuet0M8A1zpqMtbyxFgTNcIt2js8knPlDMeA5xJvLp6ZOeXNIdf2YcFZhEoHY8Z1c0sn7IabN18=
  file: tt
