sudo: required

env:
  global:
  - VLC_ANDROID_TAG=3.1.6

services:
- docker

script:
- echo "testcontent a" > ./testfilea.dummy
- echo "testcontent b" > ./testfileb.dummy

deploy:
  provider: releases
  api_key:
    secure: fFrSRuYV7eh3leJVO8EqvxkQk1stfUJ3uO51lVESGpvsMFNbHOy4EqR/3xGICoQkefZg1CjkE6z1Xft/G5XDF57WJu0V27w8ezu5sA88prc8ZejQr/3m6Xj2sC1M6HwDIffIP3Hc2n7wLWlzF2GFgijP4K7Z9Jcd3TOwSuXyrW1S/JnIxvozB+Mb3cmxbNWCHy6DQgIn5TeFLQgFjraUEHU8ChERYcOc2CwOWl6cVj1qnG5M//oR+PRdMPsf/UlOJaVAdNgZLskxoJJ7S3MEbn9QM6A/uQJfTeNMUPnV95/vaKL/5U53kksKaoJX7ajNCR3AeASbOSq/IQfm3nH4lcDWRI7a/asNvLDxzCq1/vJ73C5RPXYUT7vZmptpdU5o9TEZ7CGd/v18DMOjYKDyEDNBmBXQUJ0j4VFqi4dncnzsWiqOPL1yMiyWezaKlnnrz0+XpXnkTry5eFKruB0MGZGOvR7HlzXU/BkMKjk3ToqfysIzTOUt75hzz5lqmryxx2hhk895YZ3hC5cclv/wrSGXtaMGe5dao5QaZFO8CWW4VBiHfCgZUUoroT/C7oFnoGmp+8mVGGGCZNUUWzKJ0evIP8UQHU74locw/GT6v7cL5p/uBrDz4PpBgPBxs57iEA881wQXDRp0PhD29yg5SuT522jvVLMkq8LrI2CPTsM=
  file_glob: true
  file: "./*.dummy"
  on:
    tags: true
